In [1]:
import pandas as pd
import os

In [2]:
path= '../data/'
files = [path + file for file in os.listdir(path) if file.endswith(('.xlsx'))]

files

['../data/Cococola_SRsCategorizedDump_1.xlsx',
 '../data/Nokia_Incident_v.2.xlsx',
 '../data/Nokia_Service Request.xlsx',
 '../data/Olympics_Incident.xlsx',
 '../data/OTSUKA_Inc_6 months_1 .4.xlsx',
 '../data/Pfizer Ticket Data _Aug19_Jan20 YT Graph.xlsx',
 '../data/SAP AMS Incidents 20200630 v2.xlsx']

In [3]:
def save_df(df: pd.DataFrame, name: str):
    df.to_csv(
        path + name.split('/')[-1].split('.')[0] + '.csv',
        index=False
    )

In [4]:
dataframes = dict()

In [5]:
dataframes['cococola'] = pd.read_excel(files[0], sheet_name=0)
dataframes['cococola'].tail()

,Created,Number,Short description,Description,Month,Priority,Assignment group,Assigned to,Status,Category,Service,Resolved at,MTTR,Catalog item path,Category_1,Subcategory_1
32061,2020-01-01 01:42:53,RITM0934210,Firefighter,For a more detailed view on the requested and ...,Jan,2 - Normal,G SNOW EXT ATOS CENTRAL USER ACCESS TEAM,Dilyana Sirakova-Dimova,Closed,Firefighter,Firefighter ID Management,2020-01-01 08:28:48,0.281887,Service Catalog / User Access / SAP / Firefig...,Access Related,access Issues
32062,2020-01-01 01:40:54,RITM0934208,Remote Access,For a more detailed view on the requested and ...,Jan,2 - Normal,G SNOW RU ON-SITE Saint-Petersburg,NaN,Closed,Remote Access,Citrix NetScaler Gateway,2020-01-01 10:41:32,0.375440,Service Catalog / User Access / More Applicat...,Access Related,access Issues
32063,2020-01-01 01:35:44,RITM0934203,Wave 2,For a more detailed view on the requested and ...,Jan,2 - Normal,G SNOW PL SERVICE DESK,NaN,Closed,Wave 2,BSO Organizational Assignment,2020-01-01 06:52:43,0.220127,Service Catalog / User Access / SAP / Wave 2...,Access Related,access Issues
32064,2020-01-01 01:33:44,RITM0934201,HPQC,For a more detailed view on the requested and ...,Jan,2 - Normal,G SNOW EXT ATOS CENTRAL USER ACCESS TEAM,Bhargav MSK,Closed,HPQC,Create/ Modify /Delete User,2020-01-06 12:01:13,5.435752,Service Catalog / User Access / More Applicat...,Access Related,access Issues
32065,2020-01-01 01:32:42,RITM0934200,Remote Access,For a more detailed view on the requested and ...,Jan,2 - Normal,G SNOW EXT ATOS CENTRAL USER ACCESS TEAM,Georgi Atanasov,Closed,Remote Access,Citrix NetScaler Gateway,2020-01-01 10:44:19,0.383067,Service Catalog / User Access / More Applicat...,Access Related,access Issues

In [6]:
save_df(df=dataframes['cococola'], name=files[0])

In [9]:
dataframes['nokia_incident'] = pd.read_excel(files[1], sheet_name='Incident')
dataframes['nokia_incident'].head()

,number,approval_set,assignment_group,calendar_duration,sys_created_by,sys_created_on,closed_at,description,priority,u_service,short_description,u_support_offering_causing_the_incident,u_task_support,u_support_scope_1,u_incident.number,Category,Sub Category
0,CAL3514225,NaN,SD_1stL_SD-UC_NSN_ENG_PH,684406,amadorpa,2020-06-30 23:53:47,2020-07-08 22:00:33,"Dear team, \nCould you please give Access to S...",4 - Low,Source and Deliver Offering,NAM region - Need Access for secondary users t...,Logistic COVER,NaN,Full,INC2119203,Access Related,Access Issues
1,CAL3514223,NaN,SD_1stL_SD-UC_NSN_ENG_PH,1091361,nova.user,2020-06-30 23:51:39,2020-07-13 15:01:00,Computer_Serial_Number: PF0ZVJYE\n\nComputer_N...,4 - Low,End User Computing Offering,PC Hardware: Power Adapter or Charger concerns,Workstation Onsite Support,NaN,Full,INC2119504,Hardware Related,Adapter Issues
2,CAL3514222,NaN,SD_1stL_SD-UC_NSN_ENG_PH,680999,alanchev,2020-06-30 23:50:58,2020-07-08 21:00:57,I am locked out of Help Desk: Case Handling on...,4 - Low,Customer Care Offering,"Unable to get Access to ""Help Desk : Case Hand...",Support portal,NaN,Full,INC2119189,Access Related,Access Issues
3,CAL3514216,NaN,SD_1stL_SD-UC_NSN_ENG_PH,854190,rest.jboss.esb,2020-06-30 23:44:21,2020-07-10 21:00:51,== Diagnosis ==\r\n\r\nNUNKI P-NUN-10_101-NOKI...,3 - Moderate,IT Security Offering,P-NUN-10_101-NOKIA - Authentication: Multiple ...,Security Incident Management,NaN,Full,INC2119116,Access Related,Login Issues
4,CAL3514207,NaN,SD_1stL_SD-UC_NSN_ENG_PH,610078,pmouttou,2020-06-30 23:32:08,2020-07-08 01:00:06,SQ24-07 (10.183.129.207) located in ohn104 is ...,4 - Low,R&D and Services Cloud Offering,SQ24-07 (10.183.129.207) in ohn104 is going do...,NESC,NaN,Full,INC2119082,Server Related,Server Down

In [10]:
save_df(df=dataframes['nokia_incident'], name=files[1])

In [11]:
dataframes['nokia_service'] = pd.read_excel(files[2], sheet_name='Service Request for 6 months')
dataframes['nokia_service'].head()

,number,u_task_support,sys_created_on,closed_at,sys_created_by,opened_by,u_task_support.u_name_original,u_task_support.parent.name,u_service.name,description,u_supporting_service,short_description,Category,Sub Category
0,RITM2646029,NaN,2020-06-30 23:57:50,2020-07-09 00:14:15,luisanto,VILLA LUIS ANTONIO,NaN,NaN,NaN,NaN,SAP P20 Logistics,Document Status Update,NaN,NaN
1,RITM2646028,NaN,2020-06-30 23:56:17,2020-07-06 11:35:01,asulliva,Anne Sullivan,NaN,NaN,IT Internal Offering,NaN,Service Now,MDM: Update IT Service Offering,Data Related,MDM: Update IT Service Offering
2,RITM2646027,NaN,2020-06-30 23:55:09,2020-07-01 04:51:29,ida41064,Andy Triyono,NaN,NaN,End User Computing Offering,NaN,Workstation,Project Online Essentials - Install,NaN,NaN
3,RITM2646026,NaN,2020-06-30 23:54:20,2020-06-30 23:54:56,melbehai,Mohamed El-Behairy,NaN,NaN,End User Computing Offering,NaN,Workstation,Terminate PC from Production,Hardware Issues,Terminate PC from Prod
4,RITM2646025,NaN,2020-06-30 23:52:49,2020-07-01 04:51:41,ida41064,Andy Triyono,NaN,NaN,End User Computing Offering,NaN,Workstation,Project Online Professional,Software Related,Project Online Professional

In [12]:
save_df(df=dataframes['nokia_service'], name=files[2])

In [13]:
dataframes['olympics_incident'] = pd.read_excel(files[3], sheet_name='Page 1')
dataframes['olympics_incident'].head()

,Number,short_description,Converted Desc,Search_Criteria,SubCat,Category,Verified
0,INC0903398,BON:Report the Security Alarm – Stealthwatch,"To AtoS Managers,\n\nWe report the detected St...",Security Alarm,Report Issues,Report Related,NaN
1,INC0903397,BON:Report the Security Alarm – Stealthwatch,"To AtoS Managers,\n\nWe report the detected St...",Security Alarm,Security Issues,Security Related,NaN
2,INC0860040,"Operation method, problem or consultation a...",Venue: Secondary Data Centre\nHostname: SDC-M1...,Query,Server Down,Server Related,NaN
3,INC0903269,Inquiry about electronic payment system error...,Approval system failure has been occurred and ...,nquir,General Inquiry,User Request,Yes
4,INC0903264,DMS and ITSM account termination,Please delete one account. (DMA and ITSM)\nPle...,account termin,Account Termination Request,Access Related,NaN

In [14]:
save_df(df=dataframes['olympics_incident'], name=files[3])

In [15]:
dataframes['otsuka_inc_6_months_1'] = pd.read_excel(files[4], sheet_name='Inc')
dataframes['otsuka_inc_6_months_1'].head()

,Incident_No,assigned_to,business_duration,u_assign_to_hop_count,category,child_incidents,closed_at,Close Date,sys_created_on,Open Date,...,u_task_for.u_sales_rep_type,u_task_for.u_sales_division,u_task_for.state,u_task_for.u_user_type,u_task_for.vip,caller_id.department,Blank Data,Category_2,Subcategory_2,Verify
0,INC0338572,Matt Schmaltz-CW,259200,5,Application,0,1/21/2020 0:02,21/1/2020,1/8/2020 7:25,8/1/2020,...,NaN,NaN,NaN,NaN,False,NaN,NaN,Access Related,Access Issues,Yes
1,INC0348049,Andre Vitalis-CW,172800,1,Application,0,2/12/2020 0:01,12/2/2020,2/4/2020 4:40,4/2/2020,...,NaN,NaN,NaN,NaN,False,NaN,NaN,Access Related,Login Issues,Yes
2,INC0353450,David Simmons-CW,259200,5,Application,0,3/4/2020 0:01,4/3/2020,2/20/2020 4:20,20/2/2020,...,NaN,NaN,NaN,NaN,False,NaN,NaN,Access Related,Account Enabled/ Disabled Issues,Yes
3,INC0363580,Chris Beck-CW,201600,3,Application,0,3/31/2020 0:02,31/3/2020,3/20/2020 10:45,20/3/2020,...,NaN,NaN,NaN,NaN,False,NaN,NaN,Access Related,Account Enabled/ Disabled Issues,Yes
4,INC0366444,Mayank Bajpai-CW,201600,3,Application,0,4/8/2020 0:01,8/4/2020,3/29/2020 22:52,29/3/2020,...,NaN,NaN,NaN,NaN,False,NaN,NaN,Access Related,Access Issues,Yes

In [16]:
save_df(df=dataframes['otsuka_inc_6_months_1'], name=files[4])

In [18]:
dataframes['pfizer_tkt_data'] = pd.read_excel(files[5], sheet_name='Sheet1')
dataframes['pfizer_tkt_data'].head()

,INCIDENT NUMBER,UPDATE_TIME,UPDATED_BY,ORIGINATING_CALL,ORIGINATING GROUP,OPEN_TIME,OPENED_BY,ASSIGNMENT_GROUP,ASSIGNEE,STATUS,...,SUBCATEGORY,PFZ_RB_PHONE,PFZ_ASSIGNMENT,SUBTYPE,PFZ_FM_OWNER,System,Week Day,Agent Group,Hospira,Total Time
0,GRO31760551i,2020-01-27 10:49:33,NARDEJ01,NaN,GBL-BTI-GCC PROBLEM MANAGEMENT,2020-01-02 13:55:46,HELTOR,GBL-WTI-AHS UNIX DTS,RONANK02,Work in progress,...,PROBLEM MANAGEMENT,+1.810.3972302,NaN,NaN,NaN,Unix,Thursday,Offshore,NaN,NaN
1,IND31763797i,2020-01-28 01:16:53,MAHAJD05,NaN,GBL-WTI-AHS UNIX DTS,2020-01-03 07:00:23,SUKHAS02,GBL-WTI-AHS UNIX L1,MAHAJD05,Restored,...,SERVER,+1888-648-9224 - OPTION 1,GBL-WTI-AHS UNIX L2,LOGICAL,WTI,Unix,Friday,Offshore,NaN,NaN
2,AMR31765138i,2020-01-29 10:32:05,PANDIP08,WEB38105036c,AMR-WTI-EUS SERVICE DESK L1,2020-01-03 11:35:02,VILLAD19,GBL-WTI-AHS WINTEL L1,PANDIP08,Resolved,...,ACTIVE DIRECTORY,+1.248.650.6468,GBL-WTI-AHS WINTEL L2,LOGICAL,WTI,Wintel,Friday,Offshore,NaN,NaN
3,AMR31765527i,2020-01-31 11:46:15,NABORA,WEB38105488c,AMR-WTI-EUS SERVICE DESK L1,2020-01-03 13:09:49,CAMACS04,GBL-WTI-AHS WINTEL L2,PANDIP08,Restored,...,FILESHARE,UNKNOWN,GBL-WTI-AHS WINTEL L2,FARM GUEST,NaN,Wintel,Friday,Offshore,HPDRMF01,NaN
4,AMR31765765i,2020-01-27 16:39:51,VENUGM03,NaN,GBL-WTI-AHS DP L2,2020-01-03 14:25:46,ABREUA07,GBL-WTI-AHS WINTEL L1,VENUGM03,Resolved,...,BACKUP,UNKNOWN,GBL-WTI-AHS WINTEL L2,LOGICAL,WTI,Wintel,Friday,NaN,NaN,NaN

In [19]:
save_df(df=dataframes['pfizer_tkt_data'], name=files[5])

In [20]:
dataframes['sap_ams'] = pd.read_excel(files[6], sheet_name='Page 1')
dataframes['sap_ams'].head()

,Number,Caller,Severity,Opened,Closed,Resolve time,Duration,Location,Reassignment count,Short description,...,State,Resolving Group,Assigned to,SLA due,Updated,Made SLA,Has breached,Environment,Category,Subcategory
0,INC3367398,Julie Bacon,3 - Low,2019-08-14 11:51:42,NaT,3027707.0,3027707,Stockport,3,ZGRO_DELIV ERRORS,...,Closed,PZC_AMS_F2S,NaN,2019-08-27 19:34:48,2019-09-23 13:03:49,True,True,NaN,Application Related,Application error
1,INC1899496,Ninuk Setyorini,3 - Low,2018-12-26 05:06:34,2019-02-10 11:01:28,3563160.0,3563160,NaN,2,ZGR_FPAYM doesnt work for SG25,...,Closed,PZC_AMS_R2R,NaN,2019-02-03 11:52:14,2019-02-10 11:01:28,True,True,NaN,Application Related,Application error
2,INC4407193,David Tandri,3 - Low,2020-01-08 05:43:53,2020-02-26 09:07:47,3811263.0,3811263,Jakarta,2,ZGO_SALES_TRACK does not work (AU15 & NZ,...,Closed,PZC_AMS_O2C,NaN,2020-01-08 13:43:53,2020-02-26 09:07:47,True,True,NaN,NaN,NaN
3,INC3214787,Julie Bacon,3 - Low,2019-07-22 11:14:52,2019-08-12 05:00:44,1357163.0,1357163,Stockport,2,ZGO_PALREP ERROR,...,Closed,PZC_AMS_O2C,NaN,2019-08-01 14:27:04,2019-09-02 11:11:00,True,True,NaN,Application Related,Application error
4,INC5500896,Felix Khoo,3 - Low,2020-06-05 10:32:43,2020-06-14 10:02:36,340853.0,340853,Singapore,2,ZGO_MANSYS to Mansys Pre-shipper/PFI,...,Closed,PZC_AMS_P2P,NaN,2020-06-07 10:32:43,2020-06-14 10:02:36,True,True,NaN,NaN,NaN

In [21]:
save_df(df=dataframes['sap_ams'], name=files[6])